### ISSUE TITLE
Removing circular dependencies

### ISSUE THREAD

**Issue by Bakuenjin** [Bakuenjin/proxer-me-api#1]
While there aren't any circular dependencies when it comes to class structures, there are still circular requires since I mapped the Proxer.me API onto my object orientated library.

What I mean with that is for example:
The `Anime` class has a function to retrieve a list of `AnimeStream` from the server. The `AnimeStream` class has a function to retrieve the `User` that submitted / linked the `AnimeStream` on Proxer.me. The `User` class has a function to retrieve his `History`, which are his past watched `Anime` or `Manga` episodes. Since `History` objects represents `Anime` or `Manga`, the `History` class has a function to retrieve the `Anime` or `Manga` that the `History` object represents.
![image](https://user-images.githubusercontent.com/23419575/56468137-41633180-6428-11e9-835c-e5331a92fe74.png)

So, my two questions are:
* Is this even *that* bad?
* If yes, what are good ways to remove this?

Now, this is just an example above. There are some more circular dependencies and they are mostly caused by the users `TopTen` and `History`, since these both classes often close the circle with the connection back to the `Anime` or `Manga` class.

These are the results of a circular dependency check with the madge module:
![image](https://user-images.githubusercontent.com/23419575/56468186-c5b5b480-6428-11e9-8174-dd884bd3714c.png)

Any help is **highly appreciated**!

**Comment by rubengees** [comment]
I would suggest to separate concerns for these classes. These classes should only be responsible for holding data. You could introduce classes like `AnimeApi` which are then _only_ responsible for fetching data and return objects of the _data_ classes like `Anime`.

This way you could also mirror the structure of the http API, making it possible to map it's documentation directly to this module.
